# Generated by Django 4.2.1 on 2023-06-26 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_publication_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_picture'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(related_name='publiction_articles', to='myapp.publication'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='myapp.student'),
        ),
        migrations.CreateModel(
            name='ArticlePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.article')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.publication')),
            ],
        ),
    ]
